### ISSUE TITLE
Resource agent too agressive

### ISSUE THREAD

**Issue by yuqian5** [CMPUT3502020F-TerranFormer/dev_bot#14]
Resource agent too agressive at expanding. Scout agent don't get any units until 5min>.

**Comment by carter7k** [comment]
The Attack agent was too aggressive for a bit, and as a result resource tasks weren't being completed. I just changed it back (and Attack should be a lot better now)

**Comment by carter7k** [comment]
scv's are created with priority 5. If it's still too aggressive I can move back the triggers for building more command centers.

**Comment by yuqian5** [comment]
### fixed in the latest commit
